### ISSUE TITLE
Could you pwease update this to 1.20?

### ISSUE THREAD

**Issue by ItsRedlyXD** [fxmorin/ExperimentalPerformance#10]
I know it's discontinued (for now) and all but pwease, everyone needs it.

- Uwu gril

**Comment by QuanTrieuPCYT** [comment]
> I know it's discontinued (for now) and all but pwease, everyone needs it.
> 
> * Uwu gril
The mod should work just fine, the code isn't actually version-specific

**Comment by QuanTrieuPCYT** [comment]
> I know it's discontinued (for now) and all but pwease, everyone needs it.
> 
> * Uwu gril

The mod should work just fine, the code isn't version-specific

**Comment by QuanTrieuPCYT** [comment]
Can confirm that it works on 1.20

**Comment by ItsRedlyXD** [comment]
Okay, btw is someone mantaining this? I need more unsafe features bcuz using a Coda 1.1 to play mc isn't fun (so far I managed to get 50 fps in 1.19)

**Comment by FxMorin** [comment]
I will be archiving this project for now. I may improve on it one day in the future, unlikely however as im very busy.
