### ISSUE TITLE
do u plan on going back to this project? I think its very cool and would be nice to see you progress on this!

### ISSUE THREAD

**Issue by HellyTubbies** [fxmorin/ExperimentalPerformance#8]
Hey fx :D Really like this mod. I find the experiments u have been doing with this mod is really cool. do u plan on going back to this project by any chance or are u still focusing on that client u have been making? cheers :)

**Comment by fxmorin** [comment]
Eventually I would like to. Sadly im a single person and im working on 6 popular mods, and a job. So I currently don't have the time

**Comment by HellyTubbies** [comment]
I understand. :)
